https://numpy.org/devdocs/user/quickstart.html

In [2]:
import numpy as np

a = np.arange(15).reshape(3,5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a = np.array([2, 3, 4])

a

array([2, 3, 4])

In [4]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [6]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [7]:
from numpy import pi
np.linspace(0, 2, 9)   

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
print(a)

[2 3 4]


In [9]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [10]:
print(np.arange(24).reshape(2, 3, 4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [16]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a-b)
print(np.sin(a))
print(a < 35)

[20 29 38 47]
[ 0.91294525 -0.98803162  0.74511316 -0.26237485]
[ True  True False False]


In [20]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

print(A*B)
print(A @ B)
print(A.dot(B))

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
